import {createIconSetFromFontello} from 'react-native-vector-icons';
import config from './config.json';
export default createIconSetFromFontello(config, 'fontello');

export const iconNames = {
    AVATAR: 'avatar',
    GRAPH: 'bar-chart',
    COMMENT: 'comment',
    DOLLAR: 'dollar',
    LETTER: 'email',
    HIGHFIVE: 'high-five',
    HOME: 'home',
    LIKE: 'like',
    MENU: 'menu',
    PLUS: 'plus-sign',
    SEARCH: 'search',
    STAR: 'star',
    MONEY_BAG: 'money-bag',
    FULL_MONEY_BAG: 'full-money-bag',
    COLLAGE: 'collage',
    ROTATE: 'rotate',
    TEXT: 'text',
    DESIGN: 'design',
    CLOSE: 'close',
    MALE: 'male',
    FEMALE: 'female',
    RIGHT_CHEVRON: 'right-chevron',
    LEFT_CHEVRON: 'left-chevron',
    SHARE: 'share',
    FLIP: 'flip',
    LIVE: 'live',
    HEART: 'heart',
    TIMER: 'timer',
    STORY: 'story-spinner',
    INFO: 'information',
    VISIBLE: 'visible',
    INVISIBLE: 'invisible',
    HISTORY: 'history',
    LOGOUT: 'logout',
    FLASH: 'flash',
    FULL_HEART: 'full-heart',
    FOLLOW: 'follow',
    CONFIRM: 'confirm',
    CAMERA: 'camera',
    EARN: 'earn',
    SEND: 'send',
    COMMENT_SQUARE: 'comment-1',
    FULL_EARN: 'full-earn',
    FULL_COMMENT: 'full-comment',
    FULL_SHARE: 'full-share',
    LOCK: 'lock',
    BANK: 'bank',
    BANK2: 'bank-2',
    TOP: 'award',
    FULL_TOP: 'full-top',
    CALENDAR: 'calendar',
    TRASH: 'trash',
    DOC: 'doc',
    LAW: 'law'
}
